version: '3.8'

services:
  web:
    image: app-name:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    image: alpine:latest
    volumes:
      - dbdata:/var/lib/sqlite
    command: sh -c "apk add --no-cache sqlite && touch /var/lib/sqlite/db.sqlite"

volumes:
  dbdata:
